// Code generated by lister-gen. DO NOT EDIT.

package v1

// StudentListerExpansion allows custom methods to be added to
// StudentLister.
type StudentListerExpansion interface{}

// StudentNamespaceListerExpansion allows custom methods to be added to
// StudentNamespaceLister.
type StudentNamespaceListerExpansion interface{}
