// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s_customize_controller/pkg/client/clientset/versioned/typed/bolingcavalry/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBolingcavalryV1 struct {
	*testing.Fake
}

func (c *FakeBolingcavalryV1) Students(namespace string) v1.StudentInterface {
	return &FakeStudents{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBolingcavalryV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
