// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	bolingcavalryv1 "k8s_customize_controller/pkg/apis/bolingcavalry/v1"
	versioned "k8s_customize_controller/pkg/client/clientset/versioned"
	internalinterfaces "k8s_customize_controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s_customize_controller/pkg/client/listers/bolingcavalry/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StudentInformer provides access to a shared informer and lister for
// Students.
type StudentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.StudentLister
}

type studentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStudentInformer constructs a new informer for Student type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStudentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStudentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStudentInformer constructs a new informer for Student type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStudentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BolingcavalryV1().Students(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BolingcavalryV1().Students(namespace).Watch(context.TODO(), options)
			},
		},
		&bolingcavalryv1.Student{},
		resyncPeriod,
		indexers,
	)
}

func (f *studentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStudentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *studentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bolingcavalryv1.Student{}, f.defaultInformer)
}

func (f *studentInformer) Lister() v1.StudentLister {
	return v1.NewStudentLister(f.Informer().GetIndexer())
}
