// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "k8s_customize_controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Students returns a StudentInformer.
	Students() StudentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Students returns a StudentInformer.
func (v *version) Students() StudentInformer {
	return &studentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
